source 'https://rubygems.org'

ruby '2.1.1'
gem 'parse-ruby-client'
gem 'hashie'
gem 'rake'
gem 'debugger'

#group :test do
  #gem 'shoulda-context'
  #gem 'shoulda'
  #gem 'shoulda-matchers', '1.4.1'
  #gem 'minitest'
  #gem 'vcr'
  #gem 'webmock', '1.8.0'
#end
